"""Rasterize the menu's Chinese subset as antialiased RGB565-ready glyphs."""

from pathlib import Path
import argparse

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parent
FONT_PATH: Path
TEXT = (
    "主菜单关卡选择设置关于返回键退出关于暴力摩托"
    "原版：ROAD RASH平台：3DO年份：1994"
    "发行：Electronic Arts类型：摩托竞速格斗"
    "移植：BBK 9588移植作者：HelloClyde"
    "赞助：唔识游水的鱼??步步高电子词典游戏群（830340878）"
    "群号：830340878返回键返回"
    "等级金币车辆开始比赛购买车辆余额不足加载失败存档失败"
    "价格场次最佳公路峡谷城市纳帕综合音乐开关确认键切换"
)
LARGE_TEXT = "暴力摩托关卡选择设置关于音乐：开关"


def glyph(font: ImageFont.FreeTypeFont, char: str, width: int,
          height: int, y_offset: int, advance: int) -> str:
    image = Image.new("L", (width, height), 0)
    ImageDraw.Draw(image).text((0, y_offset), char, font=font, fill=255)
    shades = [min(15, (pixel + 8) // 17) for pixel in image.tobytes()]
    packed = [(shades[i] << 4) | shades[i + 1]
              for i in range(0, len(shades), 2)]
    if char != " " and not any(packed):
        raise ValueError(f"Empty menu glyph: {char!r}")
    data = ", ".join(str(byte) for byte in packed)
    return f"    {{{ord(char)}u, {advance}u, {{{data}}}}},"


def generate_table(chars: list[str], font_size: int, width: int,
                   height: int, y_offset: int, struct_name: str,
                   table_name: str, count_name: str) -> list[str]:
    font = ImageFont.truetype(str(FONT_PATH), font_size)
    font.set_variation_by_name("Medium")
    lines = [
        f"typedef struct {struct_name} {{",
        "    unsigned int codepoint;",
        "    unsigned char advance;",
        f"    unsigned char alpha[{width * height // 2}];",
        f"}} {struct_name}_t;",
        f"static const {struct_name}_t {table_name}[] = {{",
    ]
    for char in chars:
        advance = font_size if ord(char) > 127 else max(
            4, min(width, round(font.getlength(char))))
        lines.append(glyph(font, char, width, height, y_offset, advance))
    lines.extend(["};", f"#define {count_name} {len(chars)}u", ""])
    return lines


def main() -> None:
    global FONT_PATH
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", required=True, type=Path,
                        help="path to a Noto Sans SC variable TTF")
    FONT_PATH = parser.parse_args().font
    if not FONT_PATH.is_file():
        raise SystemExit(f"Noto Sans SC font not found: {FONT_PATH}")
    small = sorted(set(TEXT) | {chr(i) for i in range(32, 127)})
    large = sorted(set(LARGE_TEXT))
    lines = [
        "/* Noto Sans SC 14/20px menu subsets; generated by generate_ui_font.py. */",
        "#define ROAD_UI_SMALL_WIDTH 16u",
        "#define ROAD_UI_SMALL_HEIGHT 18u",
        "#define ROAD_UI_LARGE_WIDTH 22u",
        "#define ROAD_UI_LARGE_HEIGHT 24u",
        "",
    ]
    lines += generate_table(small, 14, 16, 18, -2, "road_ui_glyph",
                            "g_road_ui_glyphs", "ROAD_UI_GLYPH_COUNT")
    lines += generate_table(large, 20, 22, 24, -3,
                            "road_ui_large_glyph", "g_road_ui_large_glyphs",
                            "ROAD_UI_LARGE_GLYPH_COUNT")
    (ROOT / "road_ui_font.h").write_text("\n".join(lines) + "\n",
                                           encoding="ascii")
    print(f"Generated {len(small)} small and {len(large)} large menu glyphs")


if __name__ == "__main__":
    main()
